apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: first-deploy
  name: first-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: first-deploy
  template:
    metadata:
      labels:
        app: first-deploy
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
          command: ["/bin/bash", "-c"] # override the default command
          args: ["sleep 5; exit 1"] # sleep for 30s then exit with an error
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
