apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: first_deploy
  name: first_deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: first_deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: first_deploy
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
